channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - pip:
    - connectorx==0.3.2
    - polars==0.20.23
    - pyarrow==13.0.0
    - torch==2.3
    - tqdm==4.66.2
